# Generated by Django 2.0.13 on 2020-02-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='percent',
            field=models.FloatField(default='0', max_length=100),
            preserve_default=False,
        ),
    ]
